### ISSUE TITLE
Byte array overflow during `Read` operation

### ISSUE THREAD

**Issue by sitole** [macos-fuse-t/go-smb2#5]
I've encountered a consistent issue with the `Read` operation, specifically when attempting to download large files (10MB+) from an SMB Share to a local folder on my computer using Mac Finder. The operation crashes every time for files that necessitate multiple `Read` calls, indicating a problem with handling concurrent counting during `Read` packet / request processing.

### Steps to Reproduce
1. Attempt to read/move a larger file (I test it with 10MB+ files) from an SMB Share (for example to local folder using Finder).
2. Observe that the operation fails and causes a crash every time.

### Context
- This issue was first noticed yesterday. It's unclear whether it has always been present or if it's a new issue.
- The library had been working correctly in the past. To eliminate the possibility of recent changes on my end introducing this bug, I cloned the repository again and found that the issue persists, suggesting it is not related to any modifications I might have made.
- Considering a potential link to a Go version update, I tested with three different versions of Go after noticing a software update via Brew a few days ago. However, the issue occurs across all tested Go versions, which may indicate that the problem is not directly related to the Go version.

It's worth mentioning that write operations and other file manipulations work without any issues. The problem is specifically tied to reading larger files, where multiple `Read` calls are required.

## My setup
- MacBook Air M2 
- MacOS Sonoma 14.3.1, also tried before upgrade
- GO version `1.22.0 darwin/arm64` installed via Brew (tried also 1.21.6 and 1.21.5)

This is place where overflow happened every time, its clear that it must be some form of parallel change value of `d.p` because lines before that exactly handles possible case of overflow very transparently. Also I was able to catch crash via debugger when I checked memory exactly before `d.ci[d.p] ^= c` and `d.p` was In range of `d.ci`. 

https://github.com/macos-fuse-t/go-smb2/blob/1e1b5ce63fd7e892b7efd4ffa10ac2d1012c36a0/internal/crypto/cmac/cmac.go#L104

## Possible fix

I tried to resolve this by removing async execution via removal of `go func()` and then it starts working,
but iam not sure about some consequences of my solution.

https://github.com/macos-fuse-t/go-smb2/blob/1e1b5ce63fd7e892b7efd4ffa10ac2d1012c36a0/server/file_tree.go#L609-L618

Screenshot of debugger where is exactly spot of overflow.
<img width="1110" alt="image" src="https://github.com/macos-fuse-t/go-smb2/assets/31341350/29b118ff-9e93-4395-81d6-04d35d9594b6">

**Comment by sitole** [comment]
If I can do anything to help you replicate iam here to help. Also I can try to run modified version to try it out.

**Comment by macos-fuse-t** [comment]
perhaps a lock is needed in the sign() func. I'll check and let you know

**Comment by macos-fuse-t** [comment]
should be fixed now. Feel free to re-open if the problem persists
