### ISSUE TITLE
Not compatible types for Linux ARM build

### ISSUE THREAD

**Issue by sitole** [macos-fuse-t/go-smb2#6]
I want to build binary output for Linux ARM machines, 
during build iam receiving following error (for all arguments here).

`vfs/fileinfo_linux.go:19:22: cannot use sysStat.Atim.Sec (variable of type int32) as int64 value in argument to time.Unix`

```bash
export GOARCH=arm
export GOOS=linux

go build .
```

**Comment by sitole** [comment]
If casting value is enough I will send PR but I guess there will be issue with different sizes on ARM vs x86 machines so there will be needed some additional logic for handling.

**Comment by macos-fuse-t** [comment]
If Instead of casting , you put a platform dependent code in a separate
file that would be a better solution
